version: "3.7"

services:
  automation-node-develop:
    hostname: automation-node-develop
    image: automation-node-develop
    restart: always
    build:
      context: .
      target: dev
    ports:
      - 9229:9229
    volumes:
      - ./src:/app/src:cached
    env_file:
      - conf/.env
