version: "3.7"

services:
  automation-node-develop:
    hostname: automation-node-develop
    image: automation-node-develop
    restart: always
    build:
      context: .
      args:
        - NODE_ENV=develop
    command: ["make", "dev"]
    develop:
      watch: 
        # sync static content
        - path: ./src
          action: sync
          target: /app
          ignore:
            - node_modules/
