version: "3.7"

services:
  automation-node-prod:
    hostname: automation-node-prod
    image: automation-node-prod
    restart: always
    build:
      context: .
      args:
        - NODE_ENV=production
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
secrets:
  master_key:
    file: .env.keys
