name: Build

on:
  push:
    branches-ignore:
      - "main"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    env:
      NPM_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      ORACLE_NODE_PK: ${{ secrets.ORACLE_NODE_PK }}
      RPC_DEV: ${{ secrets.RABBIT_RPC_DEV }}
      RPC_STG: ${{ secrets.RABBIT_RPC_STG }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: docker compose build;