
name: Build and Deploy to Stage ENV

on:
  release:
    types: [published]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    env:
      NPM_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      ORACLE_NODE_PK: ${{ secrets.ORACLE_NODE_PK }}
      RPC: ${{ secrets.GOERLI }} 
      NETWORK: ${{ vars.GOERLI_STG }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: docker compose -f docker-compose.stage.yml build;

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - 
      name: Deploy
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        ARGS: "-rltgoDzvO"
        SOURCE: "."
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: /root/fake-oracle-nodes
        SCRIPT_BEFORE: |
          ls -al
        SCRIPT_AFTER: |
          ls -al
          echo $RSYNC_STDOUT
    - 
      name: Run Docker Container
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: 
          export NPM_TOKEN=${{ secrets.PERSONAL_GITHUB_TOKEN }} ORACLE_NODE_PK=${{ secrets.ORACLE_NODE_PK }} RPC=${{ secrets.GOERLI }} NETWORK=${{ vars.GOERLI_STG }};
          cd /root/fake-oracle-nodes;
          docker compose -f docker-compose.stage.yml down;
          docker compose -f docker-compose.stage.yml up --build -d